security:
    # Configuration du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # Configuration des fournisseurs d'utilisateurs (providers)
    providers:
        users_in_memory:
            memory:
                users:
                    admin: { password: '$2y$13$...', roles: ['ROLE_ADMIN'] }

        users_in_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database 
            entry_point: form_login
            custom_authenticator: App\Security\AppCustomAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: /

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

            switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
